### ISSUE TITLE
Using your script to build docker image

### ISSUE THREAD

**Issue by gorzynsk** [VirusPilot/ogn-pi34#2]
Hello,

I've used your script to successfully run OGN receiver on RPi together with ADSB setup done with [Mikenye Docker Containers]( https://github.com/mikenye/docker-readsb-protobuf).

I'd like to make similar Docker images and configuration as those for ADSB, but for OGN. I'd like to use you work and therefore I would like to ask for the permission to reuse your script. I can clone the script directly from your repository or just use it's content so you don't have to worry about breaking Docker part.

Thanks again for your great work
Jakub Gorzynski, SQ2WB

**Comment by VirusPilot** [comment]
Sure, feel free to reuse it.
