### ISSUE TITLE
Segmentation fault with the arm64 ong-decode

### ISSUE THREAD

**Issue by JacquesGr** [VirusPilot/ogn-pi34#3]
When running the arm64 binaries on RPI or OrangePi, the ogn-decode crashes with "Segmentation fault" it can take from 5 seconds to 1 minute until it crashes.

**Comment by VirusPilot** [comment]
I have already informed the developer but I am afraid he could only fix it by compiling the lib on an OrangePi board which he may not have available.

**Comment by pjalocha** [comment]
Would you try a more recent version ?
0.2.9 is code in developement and bugs/features are being fixed - you could if it still crashes ?

**Comment by VirusPilot** [comment]
I can't reproduce the seg fault, I am just running the latest libs on a Pi3, bullseye updated to latest version.

**Comment by JacquesGr** [comment]
@VirusPilot 
VirusPilot The issue is only on arm64 if you type uname -a it should show something like this "Linux ogntest 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux" with aarch64 

@pjalocha 
If I can download 0.2.9 from somewhere, I can try on both RPI 64 and OrangePi 64

The issue is masked because the RPI running a 64bit OS can run the 32bits binaires and appears to work but RPI 64bits OS and 64 bits binaries do not work.
The OrangePI can only run 64 bits OS and 64 bits binaries and does not work.

**Comment by VirusPilot** [comment]
Here in this repository we are hosting the latest 0.2.9 version, @pjalocha just wanted to be sure that you are using it rather than an earlier 0.2.9 version. I will try to reproduce it but had no seg faults so far.
