### ISSUE TITLE
No frequency hopping in AU

### ISSUE THREAD

**Issue by nowiresfil** [VirusPilot/ogn-pi34#5]
Hello, I'm Phil from Australia 
I have a freshly installed RPi4 running 0.2.9-arm64, built using the links and scripts here.
Noticed in 0.2.9 that frequency hopping no longer works. 
I have added RF.FreqPlan=3; into the configuration (per previous 0.2.8 config) and set OGN centre frequency to 916.2 (per previous 0.2.8) but that doesn't start the channel hopping. Since 0.2.9 the receiver is always on 916.2Mhz
Is it a bug, or is there new configuration option required?

**Comment by VirusPilot** [comment]
Hi Phil,

I forwarded your issue to the provider of the lib (@pjalocha), 0.2.9. should work similar to 0.2.8.

**Comment by pjalocha** [comment]
> Hello, I'm Phil from Australia I have a freshly installed RPi4 running 0.2.9-arm64, built using the links and scripts here. Noticed in 0.2.9 that frequency hopping no longer works. I have added RF.FreqPlan=3; into the configuration (per previous 0.2.8 config) and set OGN centre frequency to 916.2 (per previous 0.2.8) but that doesn't start the channel hopping. Since 0.2.9 the receiver is always on 916.2Mhz Is it a bug, or is there new configuration option required?

Please remove center frequency definiton, the hopping should do it.
Then see the status on 8080 and check if the frequency is changing ?

**Comment by nowiresfil** [comment]
That did it. Thanks a lot Pawel and VirusPilot.
