### ISSUE TITLE
No aircraft received with RTL-SDR Blog V4 dongle

### ISSUE THREAD

**Issue by umalavasic** [VirusPilot/ogn-pi34#7]
When using the latest binaries on a Raspberry Pi with the new RTL-SDR Blog V4 dongle, no aircraft are being received. However, when swapping the V4 for a V3 dongle, the setup functions correctly. Tried with two different V4 dongles, suggesting it is likely not a hardware defect.

**Comment by umalavasic** [comment]
I forgot to mention that this issue is related to the OGN receiver. I haven't tested the ADS-B functionality, so I'm not sure if it is affected as well.

**Comment by VirusPilot** [comment]
I am afraid you need to install a different driver for the V4, please check [https://www.rtl-sdr.com/V4/](url), section "Linux (Debian)".

**Comment by umalavasic** [comment]
Thank you, this solved the problem.

Given that the cause of this issue isn't immediately obvious and the new drivers are backwards compatible with other SDR units, I suggest including them in the standard installation process.

**Comment by VirusPilot** [comment]
I was indeed considering your idea, let me reflect further on it.

**Comment by VirusPilot** [comment]
Considering that potentially more folks are adding also an ADS-B feed based on dump1090, I suggest to add the rtl-sdr drivers according to the "Alternative Debian Package Installation Method".

**Comment by VirusPilot** [comment]
migration completed
