### ISSUE TITLE
A little more details for readme please.

### ISSUE THREAD

**Issue by miharix** [VirusPilot/ogn-pi34#8]
Hi,

firstly THANK YOU for this repo that has script that finally doesn't end in some error ! :D
(My configuration: RsPi 3 + RTL-SDR v3)

I hope for some more info an the end of README

* How to test if it works?
If I found out correctly: check https://www.gliderradar.com if your location appears
Use on RsPi "telnet localhost 30002
Go to  http://raspberrypi:8082 and http://raspberrypi:8083

* In Template.conf there is "http://raspberrypi:8080 for monitoring ADS-B traffic"
In my case that URL returns page not found. Should there be a website so you can see your live data on map before sending to OGN ?

* Where is the section of code that sends data to OGN, so one could make a local SQL copy of captured data ? (maybe telnet? today there is no traffic so I could observe)

_Ps: do you know if OGN has problems if the Position parameter would be tied to GPS (movable receiver) ?_

**Comment by VirusPilot** [comment]
Happy to hear that my script is actively used!

On the monitoring questions:

Are you sure that you have a second SDR installed? Did you successfully see some output on ports 8082 and 8083? Then also  port 8080 should show something ...

I can't tell where the code for sending is as the OGN decoder is only provided as a library.

There are setups where during startup the GPS position in Template.conf is updated accordingly.

**Comment by miharix** [comment]
"Are you sure that you have a second SDR installed" ... I didn't noticed in steps that its needed 2 RTL-SDR :) ... 
I plugged now the second one and defined for both a unique ID using
rtl_eeprom -s 0000AD0C  & rtl_eeprom -s 0000AD0B
and defined one in  rtlsdr-ogn/Template.conf and one in /etc/default/dump1090-fa

Now http://raspberrypi:8080 displays ADS-B trafic :)
telnet localhost 30002 looks like raw ADS-B packets

... now I need just to wait when there is some traffic on nearby sport airfield to se if non ADS-B receiver also works.

**Comment by VirusPilot** [comment]
some dump1090 Ports:
NET_RAW_OUTPUT_PORTS=30002 (AVR, hex)
NET_SBS_OUTPUT_PORTS=30003 (SBS, readable)
NET_BEAST_OUTPUT_PORTS=30005 (RAW, binary)

**Comment by VirusPilot** [comment]
I assume everything works fine, therefore closing the issue.
